# Generated by Django 3.2.8 on 2021-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebugLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('levelno', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('levelno', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('levelno', models.IntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
