# Generated by Django 3.2 on 2022-01-04 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debuglogentry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 19, 15, 14, 129762)),
        ),
        migrations.AlterField(
            model_name='errorlogentry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 19, 15, 14, 129762)),
        ),
        migrations.AlterField(
            model_name='infologentry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 19, 15, 14, 129762)),
        ),
    ]
