# Generated by Django 3.2.8 on 2021-11-07 13:15

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(default='', max_length=20)),
                ('is_disabled_account', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_relation', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, accounts.models.AccountInterface),
        ),
    ]
