# Generated by Django 3.2.8 on 2021-12-19 17:32

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediahandle',
            name='last_date_time_of_token_use',
            field=models.DateTimeField(default=utils.get_current_time),
        ),
    ]
