# Generated by Django 3.2 on 2022-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialmediahandle_last_date_time_of_token_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubehandlemetrics',
            name='handle',
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='follower_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='media_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='InstagramHandleMetrics',
        ),
        migrations.DeleteModel(
            name='YoutubeHandleMetrics',
        ),
    ]
