# Generated by Django 3.2 on 2022-01-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediahandle',
            name='avatar',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
