# Generated by Django 3.2.8 on 2021-11-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211120_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 18, 307812)),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 18, 308686)),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='token_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 18, 308671)),
        ),
    ]
