# Generated by Django 3.2.8 on 2021-11-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211120_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 57, 12352)),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 57, 13246)),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='rates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='token_expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 7, 59, 57, 13231)),
        ),
    ]
