# Generated by Django 3.2 on 2022-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_socialmediahandle_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='platform_specific_private_metric',
            field=models.JSONField(default=dict),
        ),
    ]
