# Generated by Django 3.2.8 on 2021-12-10 20:36

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import utils
import utils.types


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211120_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramHandleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('expired_on', models.DateTimeField(default=utils.get_handle_metrics_expire_time)),
                ('impression_data', models.JSONField(default=dict)),
                ('engagement_data', models.JSONField(default=dict)),
                ('audience_gender_data', models.JSONField(default=dict)),
                ('audience_age_data', models.JSONField(default=dict)),
                ('audience_country_data', models.JSONField(default=dict)),
                ('followers_count_data', models.JSONField(default=dict)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('last_metric_expired_on', models.DateTimeField(default=utils.get_current_time)),
                ('platform', models.CharField(default=utils.types.Platform['Instagram'], max_length=10)),
                ('reach_data', models.JSONField(default=dict)),
                ('profile_views_data', models.JSONField(default=dict)),
                ('audience_city', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeHandleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('expired_on', models.DateTimeField(default=utils.get_handle_metrics_expire_time)),
                ('impression_data', models.JSONField(default=dict)),
                ('engagement_data', models.JSONField(default=dict)),
                ('audience_gender_data', models.JSONField(default=dict)),
                ('audience_age_data', models.JSONField(default=dict)),
                ('audience_country_data', models.JSONField(default=dict)),
                ('followers_count_data', models.JSONField(default=dict)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('last_metric_expired_on', models.DateTimeField(default=utils.get_current_time)),
                ('platform', models.CharField(default=utils.types.Platform['Youtube'], max_length=10)),
                ('comments_count_data', models.JSONField(default=dict)),
                ('likes_count_data', models.JSONField(default=dict)),
                ('dislikes_count_data', models.JSONField(default=dict)),
                ('shares_count_data', models.JSONField(default=dict)),
                ('average_view_percentage_data', models.JSONField(default=dict)),
                ('positive_engagement_data', models.JSONField(default=dict)),
                ('negative_engagement_data', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SocialHandleMetrics',
        ),
        migrations.RenameField(
            model_name='socialmediahandle',
            old_name='media_uid',
            new_name='handle_uid',
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='is_refresh_token_dependent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.TextField(default='')),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(default=utils.get_current_time),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='access_token',
            field=django_cryptography.fields.encrypt(models.TextField(default='')),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='created_on',
            field=models.DateTimeField(default=utils.get_current_time),
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='token_expiration_time',
            field=models.DateTimeField(default=utils.get_current_time),
        ),
        migrations.AddField(
            model_name='youtubehandlemetrics',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmediahandle'),
        ),
        migrations.AddField(
            model_name='instagramhandlemetrics',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmediahandle'),
        ),
    ]
