# Generated by Django 3.2 on 2022-01-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20220103_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkWallTemplate',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('styles', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LinkWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.URLField(default='')),
                ('avatar_image', models.URLField(default='')),
                ('media_handles', models.JSONField(default=dict)),
                ('description', models.CharField(default='', max_length=250)),
                ('display_name', models.CharField(default='', max_length=250)),
                ('links', models.JSONField(default=dict)),
                ('styles', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tree_accounts', to='accounts.account')),
            ],
        ),
    ]
