# Generated by Django 3.2 on 2022-01-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linktree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkwallViewCounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('view_counts', models.PositiveBigIntegerField(default=0)),
                ('linkwall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linktree.linkwall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'linkwall')},
            },
        ),
        migrations.CreateModel(
            name='LinkClickCounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(default='')),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('click_counts', models.PositiveBigIntegerField(default=0)),
                ('linkwall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linktree.linkwall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'linkwall', 'link')},
            },
        ),
        migrations.AddField(
            model_name='linkwall',
            name='clicks',
            field=models.ManyToManyField(blank=True, default='', related_name='link_clicks', through='linktree.LinkClickCounterModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkwall',
            name='views',
            field=models.ManyToManyField(blank=True, default='', related_name='linkwall_views', through='linktree.LinkwallViewCounterModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
