# Generated by Django 3.2 on 2022-01-30 12:28

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('linktree', '0002_auto_20220113_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkWallLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('url', models.URLField(default='')),
                ('icon', models.URLField(default='')),
                ('type', models.CharField(default='normal', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LinkwallMediaHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=70)),
                ('url', models.URLField(default='', unique=True)),
                ('avatar', models.URLField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='linkclickcountermodel',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.RemoveField(
            model_name='linkwall',
            name='links',
        ),
        migrations.RemoveField(
            model_name='linkwall',
            name='media_handles',
        ),
        migrations.AlterUniqueTogether(
            name='linkclickcountermodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='linkwallviewcountermodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='linkclickcountermodel',
            name='click_counts',
        ),
        migrations.RemoveField(
            model_name='linkwallviewcountermodel',
            name='view_counts',
        ),
        migrations.AddField(
            model_name='linkwall',
            name='links',
            field=models.ManyToManyField(blank=True, default='', related_name='links', to='linktree.LinkWallLink'),
        ),
        migrations.AddField(
            model_name='linkwall',
            name='media_handles',
            field=models.ManyToManyField(blank=True, default='', related_name='links', to='linktree.LinkwallMediaHandles'),
        ),
    ]
