# Generated by Django 3.2 on 2022-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktree', '0003_auto_20220130_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclickcountermodel',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwall',
            name='avatar_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwall',
            name='background_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwalllink',
            name='icon',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwalllink',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwallmediahandles',
            name='avatar',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='linkwallmediahandles',
            name='url',
            field=models.TextField(default='', unique=True),
        ),
    ]
