# Generated by Django 3.2 on 2022-01-03 12:58

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20220103_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeHandleMetricModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=20)),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('expired_on', models.DateTimeField(default=utils.get_handle_metrics_expire_time)),
                ('follower_count', models.JSONField(default=dict)),
                ('media_count', models.JSONField(default=dict)),
                ('views', models.JSONField(default=dict)),
                ('comments', models.JSONField(default=dict)),
                ('likes', models.JSONField(default=dict)),
                ('dislikes', models.JSONField(default=dict)),
                ('shares', models.JSONField(default=dict)),
                ('estimated_minutes_watched', models.JSONField(default=dict)),
                ('average_view_duration', models.JSONField(default=dict)),
                ('subscriber_gained', models.JSONField(default=dict)),
                ('subscriber_lost', models.JSONField(default=dict)),
                ('viewer_percentage', models.JSONField(default=dict)),
                ('audience_watch_ratio', models.JSONField(default=dict)),
                ('relative_retention_performance', models.JSONField(default=dict)),
                ('card_impressions', models.JSONField(default=dict)),
                ('card_clicks', models.JSONField(default=dict)),
                ('card_click_rate', models.JSONField(default=dict)),
                ('card_teaser_impressions', models.JSONField(default=dict)),
                ('card_teaser_clicks', models.JSONField(default=dict)),
                ('card_teaser_click_rate', models.JSONField(default=dict)),
                ('annotation_impressions', models.JSONField(default=dict)),
                ('annotation_clickable_impressions', models.JSONField(default=dict)),
                ('annotation_clicks', models.JSONField(default=dict)),
                ('annotation_click_through_rate', models.JSONField(default=dict)),
                ('annotation_closable_impressions', models.JSONField(default=dict)),
                ('annotation_closes', models.JSONField(default=dict)),
                ('annotation_close_rate', models.JSONField(default=dict)),
                ('positive_engagement', models.JSONField(default=dict)),
                ('negative_engagement', models.JSONField(default=dict)),
                ('engagement', models.JSONField(default=dict)),
                ('meta_data', models.JSONField(default=dict)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmediahandle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramHandleMetricModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=20)),
                ('created_on', models.DateTimeField(default=utils.get_current_time)),
                ('expired_on', models.DateTimeField(default=utils.get_handle_metrics_expire_time)),
                ('follower_count', models.JSONField(default=dict)),
                ('media_count', models.JSONField(default=dict)),
                ('impressions', models.JSONField(default=dict)),
                ('reach', models.JSONField(default=dict)),
                ('audience_city', models.JSONField(default=dict)),
                ('audience_gender_age', models.JSONField(default=dict)),
                ('audience_country', models.JSONField(default=dict)),
                ('profile_views', models.JSONField(default=dict)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmediahandle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
