# Generated by Django 3.2 on 2022-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramhandlemetricmodel',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
